FROM websphere-liberty:webProfile7
MAINTAINER IBM Java engineering at IBM Cloud
{{#maven}}
COPY /target/liberty/wlp/usr/servers/defaultServer /config/
{{/maven}}
{{#gradle}}
COPY /build/wlp/usr/servers/defaultServer /config/
{{/gradle}}
# Install required features if not present
RUN installUtility install --acceptLicense defaultServer
