apiVersion: v1
kind: Service
metadata:
  name: "{{appName}}"
  labels:
    app: "{{appName}}"
    tier: frontend
spec:
  # if your cluster supports it, uncomment the following to automatically create
  # an external load-balanced IP for the frontend service.
  #type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 3000
  selector:
    app: "{{appName}}"
    tier: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: "{{appName}}"
  # these labels can be applied automatically
  # from the labels in the pod template if not set
  # labels:
  #   app: "{{appName}}"
  #   tier: frontend
spec:
  # this replicas value is default
  # modify it according to your case
  replicas: 1
  # selector can be applied automatically
  # from the labels in the pod template if not set
  # selector:
  #   matchLabels:
  #     app: "{{appName}}"
  #     tier: frontend
  template:
    metadata:
      labels:
        app: "{{appName}}"
        tier: frontend
    spec:
      containers:
      - name: "{{appName}}"
        image: registry.ng.bluemix.net/MYSPACE/MYIMAGE:latest
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        env:
        - name: GET_HOSTS_FROM
          value: dns
          # If your cluster config does not include a dns service, then to
          # instead access environment variables to find service host
          # info, comment out the 'value: dns' line above, and uncomment the
          # line below.
          # value: env
        ports:
        - containerPort: 3000
